# Generated by Django 3.2.7 on 2021-09-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('roll_no', models.IntegerField()),
                ('Class', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
